{{- if .Values.monitoring.enabled }}

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "gitlab-exporter-clickhouse-recorder.fullname" . }}
  labels:
    {{- include "gitlab-exporter-clickhouse-recorder.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "gitlab-exporter-clickhouse-recorder.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - port: {{ .Values.monitoring.port | quote }}
      path: {{ .Values.monitoring.path | quote }}
      interval: {{ .Values.monitoring.interval | quote }} 

{{- end }}
