apiVersion: 1
datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    uid: clickhouse
    isDefault: true
    jsonData:
      defaultDatabase: default
      port: 9000
      server: clickhouse
      username: $GF_CLICKHOUSE_USER
      traces:
        defaultDatabase: gitlab_ci
        defaultTable: traces
        otelEnabled: true
        otelVersion: latest
    secureJsonData:
      password: $GF_CLICKHOUSE_PASSWORD
  - name: Prometheus
    type: prometheus
    uid: prometheus
    url: http://prometheus:9090

