# Default values for gitlab-exporter-clickhouse-recorder.

nameOverride: ""
fullnameOverride: ""

image:
  registry: ghcr.io
  repository: cluttrdev/gitlab-exporter-clickhouse-recorder
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""
  pullPolicy: Always

podAnnotations: {}
podLabels: {}

podSecurityContext:
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop: [ALL]
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000

resources: {}
#  requests:
#    cpu: 100m
#    memory: 128Mi
#  limits:
#    cpu: 200m
#    memory: 256Mi

monitoring:
  enabled: &monitoringEnabled false
  port: &monitoringPort 9100
  path: /metrics
  interval: 1m

service:
  type: ClusterIP
  ports:
    grpc: 80
    http: *monitoringPort

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

nodeSelector: {}

tolerations: []

affinity: {}

env: []

# ---

# See here for all available configuration options and their default values:
# https://github.com/cluttrdev/gitlab-exporter-clickhouse-recorder/blob/main/configs/gitlab-exporter-clickhouse-recorder.yaml
config:
  server:
    host: 0.0.0.0
    port: 36275

  http:
    enabled: *monitoringEnabled
    host: 0.0.0.0
    port: *monitoringPort
