global:
  scrape_interval: "15s"

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: "1m"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "gitlab-exporter"
    static_configs:
      - targets:
          - "gitlab-exporter:9100"
          - "gitlab-exporter-clickhouse-recorder:9100"

