---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gitlab-exporter-clickhouse-recorder.fullname" . }}
  labels:
    {{- include "gitlab-exporter-clickhouse-recorder.labels" . | nindent 4 }}
data:
  config.yaml: |
  {{- tpl (toYaml .Values.config) $ | nindent 4 }}

