apiVersion: v1
kind: Service
metadata:
  name: {{ include "gitlab-exporter-clickhouse-recorder.fullname" . }}
  labels:
    {{- include "gitlab-exporter-clickhouse-recorder.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.grpc }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "gitlab-exporter-clickhouse-recorder.selectorLabels" . | nindent 4 }}
