version: '3'

name: glche-quickstart

services:
  clickhouse:
    container_name: clickhouse
    image: docker.io/clickhouse/clickhouse-server:latest
    environment:
      # variables used in ./clickhouse/initdb.d/init-db.sh
      INITDB_CLICKHOUSE_DATABASE: "gitlab_ci"
      INITDB_CLICKHOUSE_USER: "glche"
      INITDB_CLICKHOUSE_PASSWORD: "glche"
    volumes:
      - ./clickhouse/config.xml:/etc/clickhouse-server/config.d/config.xml:ro
      - ./clickhouse/users.xml:/etc/clickhouse-server/users.d/users.xml:ro
      - ./clickhouse/initdb.d/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh:ro
      - clickhouse_data:/var/lib/clickhouse/
      - clickhouse_logs:/var/log/clickhouse-server/
    networks:
      - glche-quickstart
    expose:
      - "9000"
    ports:
      - 127.0.0.1:8123:8123  # http
      - 127.0.0.1:9000:9000  # native
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  grafana:
    container_name: grafana
    image: docker.io/grafana/grafana:latest
    environment:
      - GF_INSTALL_PLUGINS=grafana-clickhouse-datasource
    volumes:
      - ./grafana/provisioning/datasources/:/etc/grafana/provisioning/datasources/
      - ./grafana/provisioning/dashboards/:/etc/grafana/provisioning/dashboards/
      - grafana_data:/var/lib/grafana
    networks:
      - glche-quickstart
    ports:
      - 127.0.0.1:3000:3000

  gitlab-exporter-clickhouse-recorder:
    container_name: gitlab-exporter-clickhouse-recorder
    image: ghcr.io/cluttrdev/gitlab-exporter-clickhouse-recorder:latest
    environment:
      GLCHE_CLICKHOUSE_HOST: clickhouse
      GLCHE_CLICKHOUSE_PORT: 9000
      GLCHE_CLICKHOUSE_DATABASE: "gitlab_ci"
      GLCHE_CLICKHOUSE_USER: "glche"
      GLCHE_CLICKHOUSE_PASSWORD: "glche"

      GLCHE_SERVER_HOST: 0.0.0.0
      GLCHE_SERVER_PORT: 36275

      GLCHE_LOG_LEVEL: debug
    networks:
      - glche-quickstart
    expose:
      - "36275"
    ports:
      - 127.0.0.1:36275:36275
    command: ["run"]

volumes:
  clickhouse_data: {}
  clickhouse_logs: {}
  grafana_data: {}

networks:
  glche-quickstart:
    name: glche-quickstart

